# Configurações de banco de dados (ajuste conforme necessário)
spring.datasource.url=jdbc:mysql://localhost:3306/influencer_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Configurações adicionais
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG

# JWT Configuration
jwt.secret=suaChaveSecretaSuperSeguraDeveTerMaisDe32Caracteres
jwt.expiration=86400000